nice-digital/consultations

- Comments/ClientApp/package-lock.json
- Comments/ClientApp/package.json
- Comments/ClientApp/src/App.test.js
- added cross-env for multi-environment environment setting
> Update test scripts for coverage and CI

- Comments/Startup.cs
- README.md
Enable server HTML rendering approvals tests with SSR
> React integration tests

- Comments/ClientApp/src/components/CommentBox/CommentBox.js
- Comments/ClientApp/src/components/CommentList/CommentList.js
- Comments/ClientApp/src/components/CommentList/__tests__/CommentList.test.js
https://nicedigital.atlassian.net/browse/EC-303
> EC-303 - Adding delete functionality.

- Comments.Test/Comments.Test.csproj
- Comments.Test/Infrastructure/TestBase.cs
- Comments.Test/IntegrationTests/API/Chapter/ChapterTests.cs
- Comments.Test/IntegrationTests/API/Consultation/ConsultationTests.cs
- Comments.Test/IntegrationTests/API/Documents/DocumentsTests.Get_Documents_Feed_Fills_In_Blank_Document_Titles.expected.txt
- Comments.Test/IntegrationTests/API/Documents/DocumentsTests.Get_Documents_Feed_Returns_Populated_Feed.expected.txt
- Comments.Test/IntegrationTests/API/Documents/DocumentsTests.cs
- Comments.Test/UnitTests/ConsultationService.Tests.cs
- Comments/Comments.csproj
- Comments/Configuration/FeedConfig.cs
- Comments/Program.cs
- Comments/Services/ConsultationService.cs
- Comments/Startup.cs
- Comments/ViewModels/Chapter.cs
- Comments/ViewModels/Consultation.cs
- Comments/ViewModels/Document.cs
- Comments/appsettings.json
https://nicedigital.atlassian.net/browse/EC-476
> EC-476 Update NICE.Feeds

- Comments.Test/Infrastructure/TestBase.cs
- Comments.Test/IntegrationTests/API/Answers/AnswersTests.cs
- Comments.Test/IntegrationTests/API/Comments/CommentTests.Insert_Multiple_Comments_And_Read_Them.expected.txt
- Comments.Test/UnitTests/AnswerService.Tests.cs
- Comments/Models/EF/ConsultationsContext.cs
- Comments/Program.cs
- Comments/Startup.cs
https://nicedigital.atlassian.net/browse/EC-479
> EC-479 Deploy to Dev and Alpha

- .gitignore
- Comments/ClientApp/src/components/CommentBox/CommentBox.js
- Comments/ClientApp/src/components/CommentBox/CommentBox.scss
- Comments/ClientApp/src/components/Document/Document.js
- Comments/ClientApp/src/components/Document/__tests__/Document.test.js
- Comments/ClientApp/src/components/Document/__tests__/__snapshots__/Document.test.js.snap
- Comments/ClientApp/src/components/StackedNav/StackedNav.js
- Comments/ClientApp/src/components/StackedNav/__tests__/StackedNav.test.js
- Comments/ClientApp/src/constants.js
- Comments/ClientApp/src/helpers/__tests__/utils.test.js
- Comments/ClientApp/src/helpers/utils.js
- Separate nav panels for 'commentable' and 'supporting' documents
- 'commentable' documents are loaded into the browser
- 'supporting' documents are downloaded
> EC-476 Documents List

- Comments/ClientApp/src/components/CommentList/CommentList.js
https://nicedigital.atlassian.net/browse/EC-305
> EC-305 Fixed Filtering issue

- Comments/ClientApp/src/components/CommentList/CommentList.js
- Comments/ClientApp/src/components/CommentList/__tests__/CommentList.test.js
https://nicedigital.atlassian.net/browse/EC-305
> EC-305 review page

- Comments/ClientApp/src/components/CommentList/CommentList.js
- Comments/ClientApp/src/index.js
https://nicedigital.atlassian.net/browse/EC-305
> EC-305 Ie11polyfill

- Comments.Test/Comments.Test.csproj
- Comments.Test/IntegrationTests/API/Consultation/ConsultationTests.Get_Consultation_Feed_Returns_Populated_Feed.expected.txt
- Comments.Test/IntegrationTests/API/Consultations/ConsultationTests.Get_Consultations_Feed_Returns_Populated_Feed.expected.txt
- Comments.Test/UnitTests/ConsultationService.Tests.cs
- Comments/Comments.csproj
- Comments/ViewModels/Consultation.cs
- Comments/ViewModels/Document.cs
https://nicedigital.atlassian.net/browse/ID-200
> ID-200 Updated NICE.Feeds

- Comments/ClientApp/src/components/Document/Document.js
- Comments/ClientApp/src/components/Document/__tests__/__snapshots__/Document.test.js.snap
- Comments/ClientApp/src/components/Document/html-transforms/chapter-section.js
- Comments/ClientApp/src/components/Document/html-transforms/internal-link.js
- Comments/ClientApp/src/components/Document/html-transforms/types.js
- Comments/ClientApp/src/components/Document/process-document-html.js
- Comments/ClientApp/src/components/Drawer/Drawer.js
- Comments/ClientApp/src/helpers/component-helpers.js
- document links now jump between sections
> EC-531 Add footnote links

- Comments.Test/IntegrationTests/API/Documents/DocumentsTests.Get_Documents_Feed_Fills_In_Blank_Document_Titles.expected.txt
- Comments.Test/IntegrationTests/API/Documents/DocumentsTests.Get_Documents_Feed_Returns_Populated_Feed.expected.txt
- Comments/Services/ConsultationService.cs
- Comments/ViewModels/Document.cs
https://nicedigital.atlassian.net/browse/ID-200
> ID-200 Update nice feeds

- Comments/Models/Comment.cs
- Comments/Services/CommentService.cs
https://nicedigital.atlassian.net/browse/EC-523
> EC-523 Time difference between saved and retrieved comments

- Comments/Common/Extensions.cs
- Comments/Controllers/Web/AdminController.cs
- Comments/Migrations/20180711125435_QuestionInsertOne.cs
- Comments/Models/Answer.cs
- Comments/Models/Context.cs
- Comments/Services/AdminService.cs
- Comments/Services/QuestionService.cs
- Comments/Services/SubmitService.cs
- Comments/Startup.cs
https://nicedigital.atlassian.net/browse/EC-591
https://nicedigital.atlassian.net/browse/EC-592
> EC-591 Script Deletion of Comments and Answers + EC-592 Answer date fix

- Comments/ClientApp/src/components/Document/Document.js
- Comments/ClientApp/src/components/Document/__tests__/__snapshots__/Document.test.js.snap
https://nicedigital.atlassian.net/browse/EC-593
> EC-593 Removing consultation level comment feature

- Comments.Test/IntegrationTests/API/Consultation/ConsultationTests.Get_Consultation_Feed_Returns_Populated_Feed.approved.txt
- Comments.Test/UnitTests/ConsultationService.Tests.cs
- Comments/ClientApp/public/sample.json
- Comments/ClientApp/src/components/Document/__tests__/Consultation.json
- Comments/ClientApp/src/components/Document/__tests__/__snapshots__/Document.test.js.snap
- Comments/ClientApp/src/components/ReviewPage/__tests__/Consultation.json
- Comments/Common/ExternalRoutes.cs
- Comments/Services/ConsultationService.cs
https://nicedigital.atlassian.net/browse/EC-568
> EC-568 Breadcrumb changes

- Comments.Test/IntegrationTests/API/Consultation/ConsultationTests.Get_Consultation_Feed_Returns_Populated_Feed.approved.txt
- Comments.Test/UnitTests/ConsultationService.Tests.cs
- Comments/ClientApp/src/components/Document/__tests__/Consultation.json
- Comments/ClientApp/src/components/Document/__tests__/__snapshots__/Document.test.js.snap
- Comments/ClientApp/src/components/ReviewPage/__tests__/Consultation.json
- Comments/Services/ConsultationService.cs
https://nicedigital.atlassian.net/browse/EC-568
> EC-568 Changing the breadcrumbs again.

- Comments/ClientApp/src/server/renderer.js
- simple try catch around some of the renderer calls to get more verbose information out of SSR node errors
> EC-594 Basic react error handling

- Comments/ClientApp/public/index.html
- Comments/ClientApp/src/components/Footer/Footer.js
- Comments/ClientApp/src/data/pre-loader.js
https://nicedigital.atlassian.net/browse/EC-568
> EC-568 Breadcrumb logging

- Comments.Test/IntegrationTests/API/Review/ReviewTests.cs
- Comments/ClientApp/flow-typed/type-defs.js
- Comments/ClientApp/src/components/AppliedFilter/__tests__/AppliedFilter.test.js
- Comments/ClientApp/src/components/CommentList/__tests__/CommentList.test.js
- Comments/ClientApp/src/components/FilterGroup/FilterGroup.js
- Comments/ClientApp/src/components/FilterGroup/__tests__/FilterGroup.test.js
- Comments/ClientApp/src/components/FilterOption/FilterOption.js
- Comments/ClientApp/src/components/FilterOption/__tests__/FilterOption.test.js
- Comments/ClientApp/src/components/FilterPanel/FilterPanel.js
- Comments/ClientApp/src/components/FilterPanel/__tests__/FilterPanel.test.js
- Comments/ClientApp/src/components/HistoryContext/__tests__/HistoryContext.test.js
- Comments/ClientApp/src/components/Question/Question.js
- Comments/ClientApp/src/components/ResultsInfo/__tests__/ResultsInfo.test.js
- Comments/ClientApp/src/components/ReviewListPage/ReviewListPage.js
- Comments/ClientApp/src/components/Sort/__tests__/Sort.test.js
- Comments/ClientApp/src/components/SortLink/__tests__/SortLink.test.js
- Comments/ClientApp/src/server/renderer.js
- Comments/Configuration/ReviewConfig.cs
- Comments/Services/CommentService.cs
- Comments/ViewModels/Consultation.cs
- Comments/ViewModels/ReviewFilterGroup.cs
- Comments/ViewModels/ReviewFilterOption.cs
- Comments/ViewModels/ReviewPageViewModel.cs
https://nicedigital.atlassian.net/browse/EC-579
> EC-579 Review filter page, changes.

- Comments/ClientApp/src/components/ReviewListPage/ReviewListPage.js
- Comments/ClientApp/src/components/ReviewListPage/ReviewListPage.scss
- Comments/ClientApp/src/main.scss
- Comments/Controllers/Web/RootController.cs
https://nicedigital.atlassian.net/projects/EC/issues/EC-579
> EC-579 Removing react-sticky from the review page.

- Comments/ClientApp/src/components/Document/Document.js
- Comments/ClientApp/src/components/Document/__tests__/__snapshots__/Document.test.js.snap
- Comments/ClientApp/src/components/ReviewListPage/__tests__/__snapshots__/ReviewListPage.test.js.snap
https://nicedigital.atlassian.net/browse/EC-579
> EC-579 Text change and updating snapshots

- Comments/ClientApp/src/components/CommentList/CommentList.js
- Comments/ClientApp/src/components/CommentList/CommentList.scss
- Comments/ClientApp/src/components/CommentList/Drawer.scss
- Comments/ClientApp/src/main.scss
- Comments/ClientApp/src/styles/variables.scss
https://nicedigital.atlassian.net/browse/EC-614
> EC-614 Link tabbing through commentlist

- Comments/ClientApp/src/components/CommentList/CommentList.js
- Comments/ClientApp/src/components/Header/Header.js
- Comments/ClientApp/src/components/Header/__tests__/__snapshots__/Header.test.js.snap
- Comments/ClientApp/src/components/ReviewListPage/ReviewListPage.js
- Comments/ClientApp/src/components/ReviewListPage/__tests__/__snapshots__/ReviewListPage.test.js.snap
- Comments/ClientApp/src/components/SubmitResponseDialog/SubmitResponseDialog.js
- Comments/ClientApp/src/components/SubmitResponseDialog/__tests__/SubmitResponseDialog.test.js
https://nicedigital.atlassian.net/browse/EC-630
> EC-630 Text amends

- Comments.Test/Comments.Test.csproj
- Comments/Auth/AuthHandler.cs
- Comments/Comments.csproj
- Comments/Common/Extensions.cs
- Comments/Controllers/Web/SecureController.cs
- Comments/Models/Context.cs
- Comments/ViewModels/Question.cs
including all dependencies, and test project etc.
you'll need to install the latest SDK or runtime for this to work: http://microsoft.com/net/download
http://nicedigital.atlassian.net/browse/EC-572
> EC-572 Updating .net core to most recent stable version: 2.1.3

- Comments/ClientApp/package-lock.json
- Comments/ClientApp/package.json
- Comments/ClientApp/src/components/CommentList/CommentList.js
- Comments/ClientApp/src/helpers/utils.js
- Comments/ClientApp/src/index.js
https://nicedigital.atlassian.net/browse/EC-635
> EC-635 IE9 comment panel issue

- Comments/appsettings.json
https://nicedigital.atlassian.net/browse/EC-633
> EC-633 Kibana Logging

- Comments.Test/Comments.Test.csproj
- Comments/ClientApp/package.json
- Comments/Comments.csproj
to .net core 2.1 versions
https://nicedigital.atlassian.net/browse/EC-572
> EC-572 Version bumps for nice.feeds and nice.auth.netcore 

- Comments/ClientApp/src/components/Answer/Answer.js
- Comments/ClientApp/src/components/Answer/__tests__/__snapshots__/Answer.test.js.snap
- Comments/ClientApp/src/components/CommentList/CommentList.js
- Comments/ClientApp/src/components/Question/__tests__/__snapshots__/Question.test.js.snap
- Comments/ClientApp/src/components/ReviewListPage/__tests__/__snapshots__/ReviewListPage.test.js.snap
- Comments/ClientApp/src/helpers/editing-and-deleting.js
https://nicedigital.atlassian.net/browse/EC-629
> EC-629 Answer delete bug

- Comments/ClientApp/src/components/Document/Document.js
- Comments/ClientApp/src/components/Document/__tests__/__snapshots__/Document.test.js.snap
https://nicedigital.atlassian.net/browse/EC-637
> EC-637 In page nav added section now working with SSR

- Comments/ClientApp/public/index.html
https://nicedigital.atlassian.net/browse/EC-632
> EC-632 Add hotjar script

- Comments.Test/Infrastructure/FakeConsultationService.cs
- Comments/ClientApp/package-lock.json
- Comments/Common/Constants.cs
- Comments/Controllers/Web/RedirectController.cs
- Comments/Services/ConsultationService.cs
- Comments/Startup.cs
https://nicedigital.atlassian.net/browse/GW-130
> GW-130 Adding support for route without chapter slug.

- Comments/Controllers/Web/AdminController.cs
- Comments/Models/Context.cs
- Comments/Services/AdminService.cs
https://nicedigital.atlassian.net/browse/EC-649
> EC-649 - adding a new question insert endpoint for Martin's new script.

- Comments/ClientApp/package-lock.json
- Comments/ClientApp/package.json
- Comments/ClientApp/src/components/AnswerBox/AnswerBox.js
- Comments/ClientApp/src/components/AnswerBox/__tests__/AnswerBox.test.js
- Comments/ClientApp/src/components/AnswerBox/__tests__/__snapshots__/AnswerBox.test.js.snap
- Comments/ClientApp/src/components/CommentBox/CommentBox.js
- Comments/ClientApp/src/components/CommentBox/__tests__/CommentBox.test.js
- Comments/ClientApp/src/components/Question/__tests__/__snapshots__/Question.test.js.snap
- Comments/ClientApp/src/components/ReviewListPage/__tests__/__snapshots__/ReviewListPage.test.js.snap
- Comments/ClientApp/src/index.js
https://nicedigital.atlassian.net/browse/EC-623
> EC-623 Comment save button now working in IE9

- Comments/ClientApp/src/components/ReviewListPage/ReviewListPage.js
https://nicedigital.atlassian.net/browse/EC-630
> EC-630 Text amends revisited

- Comments/Controllers/Web/AdminController.cs
- Comments/Models/Context.cs
- Comments/Services/AdminService.cs
https://nicedigital.atlassian.net/browse/EC-648
> EC-648 - adding an admin get data route.

- Comments/ClientApp/src/components/CommentBox/CommentBox.js
- Comments/ClientApp/src/components/Header/Header.js
- Comments/ClientApp/src/components/Question/Question.js
- Comments/ClientApp/src/components/Question/__tests__/__snapshots__/Question.test.js.snap
- Comments/ClientApp/src/components/ReviewListPage/ReviewListPage.js
- Comments/ClientApp/src/components/ReviewListPage/__tests__/CommentsReview.json
- Comments/ClientApp/src/components/ReviewListPage/__tests__/ReviewListPage.test.js
- Comments/ClientApp/src/components/ReviewListPage/__tests__/__snapshots__/ReviewListPage.test.js.snap
- Comments/ClientApp/src/helpers/editing-and-deleting.js
https://nicedigital.atlassian.net/browse/EC-644
> EC-644 Document context to comments

- Comments/ClientApp/src/components/ReviewListPage/ReviewListPage.js
- Comments/Services/CommentService.cs
https://nicedigital.atlassian.net/browse/EC-656
> EC-656 Review page bug

- Comments/ClientApp/src/components/Document/Document.js
https://nicedigital.atlassian.net/browse/EC-582
> EC-583 Hidden Supporting docs panel if theres no supporting docs

- Comments/Startup.cs
https://nicedigital.atlassian.net/browse/EC-597
> EC-597 Do not UseHttpsRedirection if in dev

- Comments/ClientApp/src/components/AnswerBox/AnswerBox.js
- Comments/ClientApp/src/components/AnswerBox/__tests__/__snapshots__/AnswerBox.test.js.snap
- Comments/ClientApp/src/components/CommentBox/CommentBox.js
- Comments/ClientApp/src/components/Question/__tests__/__snapshots__/Question.test.js.snap
- Comments/ClientApp/src/components/Review/__tests__/__snapshots__/Review.test.js.snap
https://nicedigital.atlassian.net/browse/EC-675
> EC-675 Removed placeholder text in comment and answer box

- Comments/ClientApp/flow-typed/type-defs.js
- Comments/ClientApp/src/components/Breadcrumbs/Breadcrumbs.js
- Comments/ClientApp/src/components/CommentList/CommentList.js
- Comments/ClientApp/src/components/Document/Document.js
- Comments/ClientApp/src/components/DocumentPreview/DocumentPreview.js
- Comments/ClientApp/src/components/FilterPanel/FilterPanel.js
- Comments/ClientApp/src/components/Question/Question.js
- Comments/ClientApp/src/components/Review/Review.js
- Comments/ClientApp/src/components/Submitted/Submitted.js
- Comments/ClientApp/src/helpers/accessibility-helpers.js
- Comments/ClientApp/src/styles/forms.scss
https://nicedigital.atlassian.net/browse/EC-681
> EC-681 Review page content

- Comments/ClientApp/src/components/CommentBox/CommentBox.scss
- Comments/ClientApp/src/styles/variables.scss
https://nicedigital.atlassian.net/browse/EC-679
> EC-679 Unsaved changes changes

- Comments/Common/Constants.cs
- Comments/Configuration/AppSettings.cs
- Comments/Configuration/StatusConfig.cs
- Comments/Controllers/Api/StatusController.cs
- Comments/Models/Context.cs
- Comments/Models/StatusModel.cs
- Comments/Services/StatusService.cs
- Comments/Startup.cs
- Comments/appsettings.json
https://nicedigital.atlassian.net/browse/EC-691
> EC-691 Status page.

- Comments/ClientApp/src/components/Review/Review.js
https://nicedigital.atlassian.net/browse/EC-74
> EC-74 Analytics

- Comments.Test/IntegrationTests/API/Chapter/ChapterTests.Get_Chapter_Feed_Using_Chapter_Slug_Returns_Error_Page.approved.txt
- Comments.Test/IntegrationTests/API/Chapter/ChapterTests.Get_Chapter_Feed_Using_Invalid_Ids_Throws_error.approved.txt
- Comments.Test/IntegrationTests/API/Consultation/ConsultationTests.Get_Consultation_Feed_Using_Invalid_Consultation_Id_Throws_error.approved.txt
- Comments.Test/IntegrationTests/API/Documents/DocumentsTests.Get_Documents_Feed_Using_Invalid_Consultation_Id_Throws_error.approved.txt
- Comments/ClientApp/src/server/__tests__/html-processor.test.js
- Comments/ClientApp/src/server/__tests__/renderer.test.js
- Comments/ClientApp/src/server/html-processor.js
- Comments/ClientApp/src/server/renderer.js
- Comments/Configuration/EnvironmentConfig.cs
- Comments/Startup.cs
- Comments/Views/_Layout.cshtml
- Comments/appsettings.json
- Comments/run.sh
- functional-tests/docker-compose.yml
- functional-tests/package-lock.json
- functional-tests/package.json
- functional-tests/src/features/unsavedCommentDocPage.feature
- functional-tests/src/features/unsavedCommentReviewPage.feature
https://nicedigital.atlassian.net/browse/EC-697
> EC-697 Accounts Environment

- Comments/ClientApp/src/components/AnswerBox/AnswerBox.js
- Comments/ClientApp/src/components/AnswerBox/__tests__/__snapshots__/AnswerBox.test.js.snap
- Comments/ClientApp/src/components/CommentBox/CommentBox.js
- Comments/ClientApp/src/components/Question/__tests__/__snapshots__/Question.test.js.snap
- Comments/ClientApp/src/components/Review/__tests__/__snapshots__/Review.test.js.snap
- Comments/ClientApp/src/components/SubmitResponseDialog/SubmitResponseDialog.js
https://nicedigital.atlassian.net/browse/EC-702
> EC-702 Hotjar supressing inputs

- Comments/ClientApp/src/components/AnswerBox/AnswerBox.js
- Comments/ClientApp/src/components/AnswerBox/__tests__/__snapshots__/AnswerBox.test.js.snap
- Comments/ClientApp/src/components/CommentBox/CommentBox.js
- Comments/ClientApp/src/components/Question/Question.js
- Comments/ClientApp/src/components/Question/__tests__/__snapshots__/Question.test.js.snap
- Comments/ClientApp/src/components/Review/__tests__/__snapshots__/Review.test.js.snap
Incorporates cards EC-725, EC-726, EC-727
> EC-725 A11y testing issues

- Comments/Controllers/Web/AdminController.cs
- Comments/Models/Context.cs
- Comments/Services/AdminService.cs
https://nicedigital.atlassian.net/browse/EC-745
> EC-745 Added endpoint

- Comments/ClientApp/src/components/Document/Document.js
- Comments/ClientApp/src/components/Document/__tests__/ConsultationQuestionsOnly.json
- Comments/ClientApp/src/components/Document/__tests__/Document.test.js
- Comments/Properties/launchSettings.json
https://nicedigital.atlassian.net/browse/EC-747
> EC-747 Removing the tutorial if the consultation does not support comments

- Comments.Test/UnitTests/ExportToExcel.Tests.cs
- Comments/Controllers/Api/ExportController.cs
- Comments/Services/ExportService.cs
https://nicedigital.atlassian.net/browse/EC-329
> EC-753 Download permissions for export

- Comments/ClientApp/src/components/Document/__tests__/__snapshots__/Document.test.js.snap
- Comments/ClientApp/src/document-processing/transforms/chapter-section-subsection.js
https://nicedigital.atlassian.net/browse/EC-749
> EC-749 Removing hover text for titles

- Comments/ClientApp/src/components/Document/Document.js
- Comments/ClientApp/src/components/Document/__tests__/__snapshots__/Document.test.js.snap
- Comments/ClientApp/src/components/StackedNav/StackedNav.js
…and making sure the panel isn't shown if there's no content.
https://nicedigital.atlassian.net/browse/EC-757
> EC-757 Removing the current document from the list of "Other" commentable documents

- Comments/Controllers/Web/AdminController.cs
- Comments/Models/Context.cs
- Comments/Services/AdminService.cs
https://nicedigital.atlassian.net/browse/EC-754
> EC-754 Added QS Question Endpoint

- Comments/ClientApp/package-lock.json
- Comments/ClientApp/public/index.html
- Comments/ClientApp/src/components/Document/Document.js
- Comments/ClientApp/src/components/Review/Review.js
- Comments/ClientApp/src/components/Submitted/Submitted.js
- Comments/ClientApp/src/context/UserContext.js
- Comments/ClientApp/src/helpers/editing-and-deleting.js
- Comments/ClientApp/src/helpers/tag-manager.js
- Comments/ClientApp/src/server/__tests__/html-processor.test.js
- Comments/ClientApp/src/server/html-processor.js
- Comments/ClientApp/src/server/renderer.js
https://nicedigital.atlassian.net/browse/EC-698
This is in line with Google Tag Manager account version 5
> EC-698 Analytics

- Comments/ClientApp/src/components/Selection/Selection.js
- Comments/ClientApp/src/helpers/utils.js
https://nicedigital.atlassian.net/browse/EC-756
> EC-756 IE11 selection bug for testing

- Comments/ClientApp/src/components/Header/Header.js
- Comments/ClientApp/src/components/Header/__tests__/__snapshots__/Header.test.js.snap
- Comments/ClientApp/src/styles/non-design-system.scss
https://nicedigital.atlassian.net/browse/EC-739
> EC-739 Tags for consultation status

- Comments.Test/IntegrationTests/API/Export/ExportTests.cs
- Comments.Test/UnitTests/ExportToExcel.Tests.cs
- Comments/Models/Context.cs
https://nicedigital.atlassian.net/browse/EC-769
> EC-769 Excel too many records

- Comments/ClientApp/src/components/CommentList/CommentList.js
- Comments/ClientApp/src/components/Document/Document.js
- Comments/ClientApp/src/components/Review/Review.js
- Comments/ClientApp/src/document-processing/transforms/internal-link.js
- Comments/ClientApp/src/helpers/accessibility-helpers.js
- Comments/ClientApp/src/helpers/component-helpers.js
- Comments/ClientApp/src/styles/accessibility.scss
Also removed pull focus by ID - not necessary with query selector
- https://nicedigital.atlassian.net/browse/EC-738
> EC-738 Resolve page jumping bug

- Comments/Export/ExportToExcel.cs
https://nicedigital.atlassian.net/browse/EC-768
> EC-768 Added sheet relationship

- Comments/Services/CommentService.cs
https://nicedigital.atlassian.net/browse/EC-773
> EC-773 Title name not appearing in document level question boxes on the review page

- Comments/Common/UriHelpers.cs
https://nicedigital.atlassian.net/browse/EC-776
> EC-776 Regular expression fix for many documents.

- Comments/ClientApp/src/components/CommentList/CommentList.js
- Comments/ClientApp/src/components/LoginBanner/LoginBanner.js
- Comments/ClientApp/src/components/LoginBanner/LoginBanner.scss
- Comments/ClientApp/src/components/Question/Question.js
- Comments/ClientApp/src/components/Question/__tests__/Question.test.js
- Comments/ClientApp/src/components/Question/__tests__/__snapshots__/Question.test.js.snap
- Comments/ClientApp/src/components/Review/Review.js
- Comments/ClientApp/src/main.scss
- Comments/Models/Context.cs
- Comments/Properties/launchSettings.json
- Comments/Services/CommentService.cs
- Comments/Services/ConsultationService.cs
- Comments/ViewModels/ConsultationState.cs
https://nicedigital.atlassian.net/browse/EC-800
> EC-800 Question visibility

- Comments.Test/Infrastructure/TestBase.cs
- Comments.Test/IntegrationTests/API/Comments/CommentTests.cs
- Comments.Test/IntegrationTests/API/Consultation/ConsultationTests.cs
- Comments.Test/IntegrationTests/API/Questions/QuestionsAdminTests.cs
- Comments.Test/IntegrationTests/API/Questions/QuestionsTests.Edit_Question.approved.txt
- Comments.Test/IntegrationTests/API/Questions/QuestionsTests.cs
- Comments.Test/IntegrationTests/API/Review/ReviewTests.Get_AllCommentsForConsultationForReview.approved.txt
- Comments.Test/IntegrationTests/API/Submit/SubmitTests.cs
- Comments.Test/UnitTests/AnswerService.Tests.cs
- Comments.Test/UnitTests/ConsultationContext.Tests.cs
- Comments.Test/UnitTests/ConsultationListPage.Tests.cs
- Comments.Test/UnitTests/ExportToExcel.Tests.cs
- Comments.Test/UnitTests/QuestionService.Tests.cs
- Comments.Test/UnitTests/SubmitService.Tests.cs
https://nicedigital.atlassian.net/browse/EC-810
> EC-810 QuestionTypeId issues in tests

- Comments.Test/Comments.Test.csproj
- Comments/Comments.csproj
- Comments/Startup.cs
https://nicedigital.atlassian.net/browse/IDAM-250
> IDAM-250 Updating sdk version to enforce secure cookies

- Comments/ClientApp/src/components/DocumentView/DocumentView.js
https://nicedigital.atlassian.net/browse/EC-848
> EC-848 Fixing visible accessibility message

- Comments/Controllers/Api/HealthCheckController.cs
https://nicedigital.atlassian.net/browse/STAK-18
> STAK-18 Health check endpoint

- Comments/ClientApp/src/components/App/App.js
- Comments/ClientApp/src/components/LeadInfo/LeadInfo.js
https://nicedigital.atlassian.net/browse/EC-853
> EC-853 Commenting Lead Info Page

- Comments/Services/OrganisationService.cs
https://nicedigital.atlassian.net/browse/EC-912
> EC-912 Temporarily disabling organsation name retrieval

- Comments/ClientApp/src/components/CommentList/CommentList.js
- Comments/ClientApp/src/components/Document/Document.js
- Comments/ClientApp/src/components/DocumentPreview/DocumentPreview.js
- Comments/ClientApp/src/components/Download/Download.js
- Comments/ClientApp/src/components/LoginBanner/LoginBanner.js
- Comments/ClientApp/src/components/LoginBanner/__tests__/__snapshots__/LoginBanner.test.js.snap
- Comments/ClientApp/src/components/Questions/Questions.js
- Comments/ClientApp/src/components/Review/Review.js
- Comments/ClientApp/src/components/Submitted/Submitted.js
- Comments/ClientApp/src/context/UserContext.js
- Comments/Services/OrganisationService.cs
https://nicedigital.atlassian.net/browse/EC-898
> EC-898 Login banner fixes

- Comments.Test/Comments.Test.csproj
- Comments/Comments.csproj
https://nicedigital.atlassian.net/browse/IDAM-386
> IDAM-386 Update to the identity SDK version with pagination support

- Comments.Test/UnitTests/ExportToExcel.Tests.cs
- Comments/Export/ExportToExcel.cs
https://nicedigital.atlassian.net/browse/EC-935
> EC-935 Split large content for comments and answers

- Comments/ClientApp/src/components/LeadInfo/LeadInfo.js
https://nicedigital.atlassian.net/browse/EC-906
> EC-906 Content updates

- Comments/ClientApp/src/components/Review/Review.js
- Comments/ClientApp/src/components/Review/__tests__/CommentsReview.json
- Comments/ClientApp/src/components/SubmitResponseFeedback/SubmitResponseFeedback.js
- Comments/ClientApp/src/components/SubmittedContent/__tests__/SubmittedContent.test.js
https://nicedigital.atlassian.net/browse/EC-957
> EC-957 Use correct orgname on submission as lead

- Comments.Test/Infrastructure/FakeOrganisationService.cs
- Comments.Test/UnitTests/FeatureFlagServiceTests.cs
- Comments.Test/UnitTests/OrganisationService.Tests.cs
- Comments/ClientApp/src/components/CommentList/CommentList.js
- Comments/ClientApp/src/components/Document/Document.js
- Comments/ClientApp/src/components/Download/Download.js
- Comments/ClientApp/src/context/UserContext.js
- Comments/Common/Constants.cs
- Comments/Controllers/Api/FeatureFlagController.cs
- Comments/Controllers/Api/OrganisationController.cs
- Comments/Services/FeatureFlagService.cs
- Comments/Services/OrganisationService.cs
- Comments/appsettings.json
https://nicedigital.atlassian.net/browse/EC-939
> EC-939 Feature flag to user context

- Comments/ClientApp/src/components/CommentList/CommentList.js
- Comments/ClientApp/src/components/CommentList/__tests__/CommentList.test.js
- Comments/ClientApp/src/components/Question/Question.js
- Comments/ClientApp/src/components/Review/__tests__/__snapshots__/Review.test.js.snap
- Comments/ClientApp/src/components/Review/__tests__/__snapshots__/ReviewOrgCommenter.test.js.snap
https://nicedigital.atlassian.net/browse/EC-960
> EC-960 Visibility of responses to code users

- Comments.Test/Infrastructure/FakeOrganisationService.cs
- Comments.Test/UnitTests/OrganisationService.Tests.cs
- Comments/ClientApp/src/context/UserContext.js
- Comments/Controllers/Api/OrganisationController.cs
- Comments/Services/OrganisationService.cs
https://nicedigital.atlassian.net/browse/EC-958
> EC-958 Fix signin link for cookie user

- Comments/ClientApp/src/components/Question/Question.js
- Comments/ClientApp/src/components/Review/__tests__/__snapshots__/Review.test.js.snap
- Comments/ClientApp/src/components/Review/__tests__/__snapshots__/ReviewOrgCommenter.test.js.snap
- Comments/ClientApp/src/components/Review/__tests__/__snapshots__/ReviewOrgLead.test.js.snap
https://nicedigital.atlassian.net/browse/EC-885
> EC-885 Answer inputs have unique IDs

- Comments/ClientApp/src/components/CommentBox/CommentBox.scss
- Comments/ClientApp/src/styles/non-design-system.scss
https://nicedigital.atlassian.net/browse/EC-972
> EC-972 Accessibility colour contrast of text

- Comments/ClientApp/src/components/FilterGroup/FilterGroup.js
- Comments/ClientApp/src/components/Review/__tests__/__snapshots__/Review.test.js.snap
- Comments/ClientApp/src/components/Review/__tests__/__snapshots__/ReviewOrgCommenter.test.js.snap
- Comments/ClientApp/src/components/Review/__tests__/__snapshots__/ReviewOrgLead.test.js.snap
https://nicedigital.atlassian.net/browse/EC-888
> EC-888 Add visually hidden information to label

- Comments/ClientApp/src/components/CommentList/CommentList.js
- Comments/ClientApp/src/components/CommentList/__tests__/__snapshots__/CommentList.test.js.snap
- Comments/ClientApp/src/components/Document/Document.js
- Comments/ClientApp/src/components/Selection/Selection.js
- Comments/ClientApp/src/components/SubmitResponseDialog/SubmitResponseDialog.js
https://nicedigital.atlassian.net/browse/EC-884
> EC-884 Clarify this is not a submit button

- Comments/ClientApp/src/components/CommentBox/CommentBox.js
- Comments/ClientApp/src/components/CommentList/CommentList.js
- Comments/ClientApp/src/components/CommentList/__tests__/__snapshots__/CommentList.test.js.snap
- Comments/ClientApp/src/components/Document/Document.js
- Comments/ClientApp/src/components/Question/Question.js
- Comments/ClientApp/src/components/QuestionTypes/OpenQuestion/OpenQuestion.js
- Comments/ClientApp/src/components/QuestionTypes/YNQuestion/YNQuestion.js
https://nicedigital.atlassian.net/browse/EC-889
> EC-889 Unsaved changes alert announces

- Comments/ClientApp/src/components/FilterOption/FilterOption.js
- Comments/Models/Context.cs
- Comments/Services/CommentService.cs
https://nicedigital.atlassian.net/browse/EC-965
> EC-965 Filtering by commenter

- Comments/appsettings.json
https://nicedigital.atlassian.net/browse/EC-931
https://nicedigital.atlassian.net/browse/EC-932
> EC-932 Adding missing logging sections to appsettings.json

- Comments/Startup.cs
https://nicedigital.atlassian.net/browse/EC-978
> EC-978 Add header to opt out of FLoC

- Comments/Common/Constants.cs
- Comments/Configuration/AppSettings.cs
- Comments/Configuration/FeedConfig.cs
- Comments/appsettings.json
- Comments/run.sh
https://nicedigital.atlassian.net/browse/EC-986
> EC-986 Removing IDAM feature switch for indev feed

- Comments/web.config
https://nicedigital.atlassian.net/browse/EC-999
> EC-999 Missing Http Security Headers

- Comments/ClientApp/public/index.html
- functional-tests/src/support/action/generateOrganisationCode.js
- functional-tests/src/support/action/idamGlobalnavLoginAdmin.js
Reverts nice-digital/consultations#399
> Revert "EC-1005 IDAM-481 Show The Signed In Users Name"

- Comments/ClientApp/src/components/Submitted/Submitted.js
- Comments/ClientApp/src/components/Submitted/__tests__/__snapshots__/Submitted.test.js.snap
- Comments/ClientApp/src/components/Submitted/__tests__/__snapshots__/SubmittedOrgCommenter.test.js.snap
- Comments/ClientApp/src/components/Submitted/__tests__/__snapshots__/SubmittedOrgLead.test.js.snap
- Indev.MockApi/Dockerfile
- functional-tests/Dockerfile
https://nicedigital.atlassian.net/browse/EC-1063
> EC-1063 Remove survey from Comment Collection submission page

- functional-tests/README.md
- functional-tests/docker-compose.yml
- functional-tests/package-lock.json
- functional-tests/package.json
- functional-tests/src/steps/when.ts
- functional-tests/src/support/action/logout.ts
- functional-tests/wdio.local.conf.ts
…amcity and updated test project readme
> EC-1071 Separated wdio settings for running locally and teamcity
